title: Beware of Jellyfish
creator: Joudi Al Sbeinaty
created on: 17/3/2024
languages used: html, css, javascript

description:
  This game utilizes space bar to allow the character to jump. 
  Player targets to not get stung by the jellyfish. The player uses yellow character
  on the left. Player challenges for receiving high scores. 
